name: Internship 4.0 Exercises CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Step 01 - Copying to virtual runner
        uses: actions/checkout@v2
        
      - name: Step 02 - Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          
      - name: Step 03 - Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
          
      - name: Step 04 - Build and Test ex01-arrayAdder with Maven
        run: |
          cd ex01-arrayAdder
          mvn --batch-mode --update-snapshots verify
          
